#+TITLE: Keyboard Story
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css">
* Французский батон
Посмотрим, чем отличаются клавиатуры друг от друга.
Понятно, что дополнительные панели (цифровая, стрелки и др.) обычно отсутствуют как отдельные панели в варианте клавиатур для ноутбуков.
Давайте рассмотрим подробнее основную панель.
Три ряда символьных клавиш присутствуют в любой модели, 
эти клавиши имеют квадратную форму одинакового размера. Можно сказать, что они составляют ядро клавиатуры.
Если присмотреться, основные отличия в моделях происходят на окраинах.
"Длинные" клавиши - пробел (Space, Enter, Backspace, Shift, CapsLock, Tab... - потенциальный источник изменений. 
Их можно делить или, наоборот, соединять с соседними.
Особенно нестабилен нижний ряд. 
За счет пробела можно создать новые клавиши, как справа, так и слева.
"Нарезка" справа позволяет переместить клавиши-стрелки на основную панель.
Клавиша "Enter" - единственная клавиша с замысловатой формой - может её менять,
также позволяя "выделить" место под дополнительные клавиши.             
* Ситуация на флангах
Множество горячих клавиш расположилось на левом фланге - 'z','x','c','v','s','q','a','e' - 
для левой руки. Клавиши под простые, но часто производимые действия,
а именно для перемещения/(перемещения с действием) - на правом.
Это Enter, Backspace, Delete, стрелки.
- замечание: интересно, что случается при использовании раскладки "Dworak"? Горячие клавиши привязаны к ПО их использующему, а не к ОС, поэтому они могут разбегаться по клавиатуре. 
- замечание: способы перемещения. В Vim - клавиши "h,j,k,l" или "g-j, g-k" (исторические причины, раньше стрелок не было; археология). В Emacs использующиеся сочетания с "ctrl" разбросаны по клавиатуре "С-b, C-n, C-p, C-f", являются начальными буквами соответствующих действий (back, next, previous,forward), что хорошо для начального запоминания, но не оптимально в дальнейшем (см. системы привязки). Также есть игровые раскладки стрелок: "a,w,s,d". 
* Аккорды
Если начать прикидывать, какие сочетания клавиш удобнее всего использовать (см. ниже), 
быстро приходишь к выводу, что расположение клавиш на [[https://en.wikipedia.org/wiki/Maltron][Мaltron Keyboard]], [[https://www.amazon.com/Maxi-Aids-Maltron-Keyboards-Dual-Handed/dp/B00IIP3FVA][Amazon]] именно то, что нужно.
Однако, такая форма клавиатуры, являясь удобной для набора, является не удобной для транспортировки/хранения/размещения.
То есть не является эргономичной в широком смысле.   
Рассмотрим сочетания клавиш: 
- полный аккорд "Alt-d-w-q-Shift"/(1,2,3,4,5) <- номера пальцев
- "Alt-q", "Alt-1" /(1,2)
- "Ctrl-q" /(1,2)
- "Сtrl-q" /(3,5) - не рекомендуется, ведёт к [[http://ergoemacs.org/emacs/emacs_pinky.html][Pinky Problem]]  
- На первый взгляд комбинации "Alt+F2"/(1,2) или "Esc+Tab"/(1,2) удобны. Однако, они требуют переноса основания ладони, от места ее обычного размещения при наборе.
* Рокировки по левому борту
Клавиша "CapsLock" довольно бестолковая, а "Esc" расположена достаточно далеко, что
не идеально при использовании Vim (исторические причины; археология)
Поэтому предлагают делать рокеровку "Esc" и "Tab".
Также есть другие [[http://vim.wikia.com/wiki/Avoid_the_escape_key][методы переопределения]]
Второй вариант рокеровки - "в длинную сторону": "Ctrl" и "Tab". 
Клавиша "Tab" расположена удобнее, также рекоммендуется для устранения Pinky Problem.   
- замечание: сочетание Shift-Tab называется inverse Tab.
* Сквозь игольное ушко
Клавиатура дает нам еще один пример разделения "политики" и "механизма".
Контроллер формирует скан-коды, значение которых могут произвольно трактоваться операционной системой.
- с помощью [[http://citforum.ru/operating_systems/freebsd/keyboard.shtml][клавиши Compose]] (пример на FreeBSD) и цифровой панели можно получить любой код символа. Тем самым, оставлена возможность контроля за системой при ошибках настройки.  
* Системы привязки
Различные binding systems
- система ввода Vim 
- [[http://ergoemacs.org/emacs/ergonomic_emacs_keybinding.html][эргономичная раскладка Emacs]], в частности для исключения [[https://www.emacswiki.org/emacs/RepeatedStrainInjury][Repeated Strain Injury]]  
* Археология
История раскладок, добавление дополнительных панелей, первоначальные назначения клавиш. Обозначения.
- замечание: тут можно сделать обзор клавишных обозначений, обозначений Emacs, в частности Meta.   
