#+TITLE: Operational Systems
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css">
* Загрузка системы
*Архитектура ПК. Assembler.* Организация памяти. Адресация памяти. 
Взаимодействие микропроцессора и переферийных устройств. Прерывания и порты. 
Взаимодействие (вызов) программ на ассемблере друг с другом и с программами на других языках. 
- Юров "Assembler". В частности, гл. "Архитектура ПК", "Прерывания", "Защищенный режим", "Обработка в защищенном режиме", "Модульное программирование" 
*Загрузка системы.* Устройство MBR. Использование готового загрузчика для запуска ОС. Разработка своего загрузчика и загрузка минимальной ОС. 
- статья "MBR для флешки"  
- статья "Как запустить программы без ОС"
- Brokenthron.com, "Operating System Development"
прочее:  
- Таненбаум "Архитектура ПК" 
* Устройство операционной системы 
Общие задачи операционной системы и детали реализации Linux, средства синхронизации, программирование под OC.
- лекции "программирование для Linux" (Андрей Боровский, Linux Format)
- Робачевский "Операционная система UNIX"
прочее:
- описание OC xv6  
- Роберт Лав, "Разработка ядра Linux"
- D. Rusling, "Linux Kernel"
- очень подробное описание с описанием различий в реализациях разных Unix систем: Stevens, Rago, "Advanced programming in the Unix Environment"  
- Таненбаум, "Современные Операционные Системы"  
* Разработка 
*Разработка модулей*  
- практика по работе с ядром: Алексей Соловьев, "Разработка модулей ядра ОС Linux"
*Сборка дистрибутива*
- Сборка системы и обзор пакетов "Linux From Scratch"
прочее:  
- O'Reilly, "Linux Device Drivers" 
- Исходный код некоторых программ: Арнольд Роббинс, "Linux программирование в примерах". 
- Описание цикла разработки дистрибутива "Руководство начинающего разработчика Debian".   
* Администрирование 
Общее о Linux: O'Reilly, "Running Linux"
** установка ОС из командной строки
Установка некоторых дистрибутивов производится из командной строки или 
с помощью текстового интерфейса и требует установки дополнительного ПО. 
К примеру:    
- установка базового Arch Linux. Также X Windows, Window Manager
- установка базового Debian. Также видео-драйвера, X Windows, Window Manager     
** загрузка Linux через GRUB
Система Linux имеет несколько уровней загрузки и может загружаться с
разными ядрами. Разные варианты загрузки:
- загрузчик GRUB имеет свой консольный режим 
- загрузка в консоль
- однопользовательский режим
- хак-загрузка с передачей параметра процессу init
- загрузка в другие разделы 
- загрузка/установка различных ядер
Способы восстановления:
- восстановление через консоль и chroot
- использование логов для восстановления после сбоя обновления. 
** подсистемы
- система репозиториев, apt-get; apt-mirror
- система инициализации, задания, автозагрузка 
- X-сервер, перенаправления
- хранение паролей
- права доступа; SELinux/AppArmor 
- работа с сетью из командной строки; iptables
- системы виртуализации Xen, Qemu/KVM
  
